//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKTX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccCB
    {
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string MaCB { get; set; }
    
        public virtual CanBoQuanLy CanBoQuanLy { get; set; }
    }
}
