//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKTX
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string MaHoaDon { get; set; }
        public string TenHoaDon { get; set; }
        public string MaDienNuoc { get; set; }
        public double TienPhong { get; set; }
        public System.DateTime NgayLap { get; set; }
        public Nullable<System.DateTime> NgayThu { get; set; }
        public string MSSV { get; set; }
        public bool status { get; set; }
    
        public virtual DienNuoc DienNuoc { get; set; }
        public virtual SV SV { get; set; }
    }
}
