//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKTX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phieu
    {
        public string MaPhieu { get; set; }
        public string TenPhieu { get; set; }
        public string MSSV { get; set; }
        public string MaCB { get; set; }
        public string MaPhong { get; set; }
        public System.DateTime NgayLap { get; set; }
    
        public virtual CanBoQuanLy CanBoQuanLy { get; set; }
        public virtual Phong Phong { get; set; }
        public virtual SV SV { get; set; }
        public virtual PhieuDangKyOKTX PhieuDangKyOKTX { get; set; }
        public virtual PhieuGiaHanHD PhieuGiaHanHD { get; set; }
        public virtual PhieuKyLuat PhieuKyLuat { get; set; }
    }
}
