//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKTX
{
    using System;
    using System.Collections.Generic;

    public partial class PhieuDangKyOKTX
    {
        public string MaPhieu { get; set; }
        public string HoTen { get; set; }
        public DateTime NgaySinh { get; set; }
        public string QueQuan { get; set; }
        public string LopHoc { get; set; }
        public string KhoaHoc { get; set; }
        public string Khoa { get; set; }
        public string SDT { get; set; }
        public string HeDaoTao { get; set; }




        public virtual Phieu Phieu { get; set; }
    }
}
