//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKTX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SV()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.Phieux = new HashSet<Phieu>();
        }
    
        public string MSSV { get; set; }
        public string MaHopDong { get; set; }
        public string MaPhong { get; set; }
        public string HoTen { get; set; }
        public bool GioiTinh { get; set; }
        public DateTime NgaySinh { get; set; }
        public string QueQuan { get; set; }
        public string LopHoc { get; set; }
        public string KhoaHoc { get; set; }
        public string Khoa { get; set; }
        public string SDT { get; set; }
        public string HeDaoTao { get; set; }
    
        public virtual AccSV AccSV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual HopDong HopDong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phieu> Phieux { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
